package chap06;

public class ExceptionTest {

	public static void main(String[] args) {
		try {
		method();
		}catch(ArithmeticException e) {
			
		}
	}
	static void method() throws ArithmeticException {
		int number = 100;
		int result = 0;

		for (int i = 0; i < 10; i++) {
				result = number / ((int) (Math.random() * 10));
				System.out.println(result);
		}
			
		
	
	
}
}
